### ISSUE TITLE
Undefined array key 0

### ISSUE THREAD

**Issue by edenahoussou** [Sicaa/number-to-fr-words#3]
Bonjour merci pour votre travail . 

Je suis tombé sur cette erreur en passant 0 comme ceci 

OS : Ubuntu 22
Framework : Laravel 
Php : 8.3

ucfirst(Sicaa\NumberToFrWords\NumberToFrWords::output(0)). ' ' . ' dollars'

Merci et bonne journée

**Comment by Sicaa** [comment]
Bonjour @edenahoussou,

Merci pour la remontée, c'est fixé :)

Nouvelle release : https://github.com/Sicaa/number-to-fr-words/releases/tag/1.0.1

Bonne journée
